### ISSUE TITLE
[FEAT] MainViewController HIFI에 맞게 수정 및 기능 구현

### ISSUE THREAD

**Issue by Cap0011** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#115]
## 🎯 이슈 개요
| 이슈 내용 | MainViewController 구현 |
| --- | --- |
| 마감 일자 | 2022.07.30 |

## 🏹 Todo
 - [x] 헤더 뷰 구현
 - [x] 검색 바 UI 수정
 - [x] 이미지 슬라이드 구현
 - [x] 스튜디오 컬렉션 뷰 구현
 - [x] touch area 셀렉터 구현
 - [x] 파이어베이스 연결
