### ISSUE TITLE
[FEAT] StudioDetailView 구현

### ISSUE THREAD

**Issue by jeohong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#130]
## 🎯 이슈 개요
| 이슈 내용 | StudioDetailView 구현  |
| --- | --- |
| 마감 일자 | 2022.08.01 |

## 🏹 Todo
 - [ ] 스튜디오 소개 View 구현
 - [ ] 스튜디오 클래스 View 구현
 - [ ] 스튜디오 이벤트 View 구현
