### ISSUE TITLE
[FEAT] Integration

### ISSUE THREAD

**Issue by Cap0011** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#149]
## 🎯 이슈 개요
| 이슈 내용 | Integration |
| --- | --- |
| 마감 일자 | 2022.08.03 |

## 🏹 Todo
 - [x] StudioDetailViewController에 들어갈 스케줄 뷰 컨트롤러 생성
 - [x] StudioDetailView pageviewcontroller 스케줄 탭 연결
 - [x] StudioDetailView pageviewcontroller 소개 탭 연결
