### ISSUE TITLE
[FEAT] 최근 검색어 기록 구현

### ISSUE THREAD

**Issue by jeohong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#15]
## 🎯 이슈 개요
| 이슈 내용 | 최근검색어 구현 |
| --- | --- |
| 마감 일자 | 2022.07.19 |

## 🏹 Todo
 - [x] NavigationBar 아래에 Divider 구현
 - [x] UserDefault에 검색어 History 저장
 - [x] 최근 검색어 Chips 형태로 구현
 - [x] CollectionView 형태로 구현
 - [x] x 버튼 누를때 목록에서 삭제 구현
