### ISSUE TITLE
[REFACTOR] DancerDetailViewController 수정

### ISSUE THREAD

**Issue by Cap0011** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#150]
## 🎯 이슈 개요
| 이슈 내용 | DancerDetailViewController 수정 |
| --- | --- |
| 마감 일자 | 2022.08.04 |

## 🏹 Todo
 - [x] 데이터 로직 생성
 - [x] 스케줄 뷰 추가
 - [x] 구독 로직 추가
 - [x] UI 하이파이대로 수정
 - [ ] 네비게이션 바 reusable로 빼기
