### ISSUE TITLE
[FEAT] DancerDetailView 커버사진 구현

### ISSUE THREAD

**Issue by LeeSungNo-ian** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#20]
## 🎯 이슈 개요
| 이슈 내용 | DancerDetailView 커버사진 구현 |
| --- | --- |
| 마감 일자 | 2022. 07 |

## 🏹 Todo
 - [ ] 커버사진 목업데이터 구현
 - [ ] 커버사진 사이즈 측정
 - [ ] 목업데이터와 연동 후 화면 구현
