### ISSUE TITLE
[FEAT] 탭바 디자인 디테일 구현

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#31]
## 🎯 이슈 개요
| 이슈 내용 | 탭바 커스터마이징 |
| --- | --- |
| 마감 일자 | 7월 14일 |

## 🏹 Todo
 - [ ] 탭바 상단 구분선 추가
 - [ ] 탭바 아이콘 추가
 - [ ] 탭바 아이템 틴트 컬러 변경
