### ISSUE TITLE
[REFACTOR] weekdayView: StackView -> CollectionView로 바꾸기

### ISSUE THREAD

**Issue by Cap0011** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#33]
## 🎯 이슈 개요
| 이슈 내용 | weekdayView 구조 CollectionView로 변경 |
| --- | --- |
| 마감 일자 | 2022.07.18 |

## 🏹 Todo
 - [x] CollectionView로 변경
 - [x] 네이밍 컨벤션 논의
 - [x] 요일 enum으로 관리
 - [x] fetchLastWeek() / fetchNextWeek() helper 함수로 중복 코드를 줄이고 변경되는 뷰만 다시 그려지도록 수정
