### ISSUE TITLE
[FEAT] 목업데이터 추가, 데이터 모델 JSON 파싱 구현

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#35]
## 🎯 이슈 개요
| 이슈 내용 | 데이터 모델 JSON 파싱 구현 |
| --- | --- |
| 마감 일자 | 2022.07.15 |

## 🏹 Todo
 - [ ] 데이터 취합 구글 폼 생성
 - [x] 엑셀 -> JSON 데이터 추출 목업 데이터 생성
 - [x] MockDataSet 클래스 생성
