### ISSUE TITLE
[FEAT] UISearchBar Design 변경

### ISSUE THREAD

**Issue by jeohong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#41]
## 🎯 이슈 개요
| 이슈 내용 | SearchBar 디자인 수정 |
| --- | --- |
| 마감 일자 | 2022.07.  |

## 🏹 Todo
 - [ ] UISearchBar 돋보기 아이콘 없애기
 - [ ] Text 크기 수정
 - [ ] navigation Bar 패딩 적ㅇ
