### ISSUE TITLE
[FEAT] 모델 데이터 수정 및  추가

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#59]
## 🎯 이슈 개요
| 이슈 내용 |  모델 데이터 수정 및  추가 |
| --- | --- |
| 마감 일자 | 2022.07.19 |

## 🏹 Todo
 - [ ] DanceClass 에 dancerID, isPopUp 프로퍼티 추가
 - [ ] Url -> URL 네이밍 수정
 - [ ] profileImageURL 목데이터에 항목 추가
 - [ ] 모델 변경사항 목데이터에 반영해서 다시 제작하기
