### ISSUE TITLE
[FEAT] SearchDetailView Detail 수정

### ISSUE THREAD

**Issue by jeohong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#66]
## 🎯 이슈 개요
| 이슈 내용 | SearchDetailView의 디테일 수정  |
| --- | --- |
| 마감 일자 | 2022.07.21  |

## 🏹 Todo
 - [ ] TableView 섹션 나누기
 - [ ] 네비게이션 바 x 버튼 누르면 이전 뷰로 전환 ( 검색어 삭제 )
 - [ ] 추천 알고리즘 고민하기
