### ISSUE TITLE
[ADD] 데이터 모델 

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#8]
## 🎯 이슈 개요
| 이슈 내용 | 데이터 모델 구현 |
| --- | --- |
| 마감 일자 | 2022.07.13 |

## 🏹 Todo
 - [x] Dancer model 구현
 - [x] Studio model 구현
 - [x] DanceClass model 구현
 - [x] Studio model 구현
