### ISSUE TITLE
[DESIGN] SubscriptionView, SubDetailCell 디자인 수정

### ISSUE THREAD

**Issue by pig1606** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#82]
## 🎯 이슈 개요
| 이슈 내용 | SubscriptionView, SubDatilCell 디자인 수정 |
| --- | --- |
| 마감 일자 | 2022.07.22 |

## 🏹 Todo
 - [x] TableView를 기본 바탕색과 일치시켜야합니다.
 - [ ] 셀 오른쪽에 화살표를 추가해야합니다.
 - [ ] 각 컴포넌츠의 constraint를 세밀하게 조정해야합니다.
