### ISSUE TITLE
[FEAT] JSON 파일 데이터 사용 및 연결

### ISSUE THREAD

**Issue by pig1606** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#83]
## 🎯 이슈 개요
| 이슈 내용 | JSON 파일 데이터 사용 및 연결 |
| --- | --- |
| 마감 일자 | 2022.07.25 |

## 🏹 Todo
 - [ ] 회색 사각형 대신 json 파일에 있는 ProfileURL을 사용해 사진을 넣어야합니다.
 - [ ] 이름, 장르, 요일 텍스트 또한 json 파일의 정보들을 가져와야합니다.
 - [ ] 각 셀을 클릭하면 PR페이지가 나오도록 연결시켜야합니다.
