### ISSUE TITLE
[REFACTOR] SearchManager 수정

### ISSUE THREAD

**Issue by jeohong** [DeveloperAcademy-POSTECH/MC3-Team3-Kongs#99]
## 🎯 이슈 개요
| 이슈 내용 | 효율적인 코드로 Refactoring |
| --- | --- |
| 마감 일자 | 2022.07 |

## 🏹 Todo
 - [x] codable 만족하는 제네릭
 - [x] Search 단어 빼기
 - [x] 파라미터 추가 ( 장르 , 댄서이름 )
 - [x] enum 으로 데이터 받기
 - [x] searchView에 firebase 연결
